### ISSUE TITLE
I hope the results can be displayed independently for the RGB channel

### ISSUE THREAD

**Issue by i-iooi-i** [oRazeD/VertexColorsPlus#1]
![image](https://github.com/user-attachments/assets/72d22825-2feb-458a-ada1-4fb3a6302e97)
![image](https://github.com/user-attachments/assets/f4175e95-2250-4f2d-822a-0adbdd8bf425)
![image](https://github.com/user-attachments/assets/47f005c6-c74b-4b98-b777-97d2be771216)
![image](https://github.com/user-attachments/assets/cb041bfa-4f61-4959-8ba0-fb2f4e930c97)

Hi there, thank you for developing the plugin, it's really great and the efficiency has improved a lot. ❤️
I am also using MAYA for my work. But I'm having a problem when Blender draws the vertex colors.  
It doesn't seem to be able to show my paintings with a separate RGB channel, 

![image](https://github.com/user-attachments/assets/69d47a37-68ab-4447-be2f-6e208d41bc95)

This is a bit of a distraction for the work that requires precise painting, and when the three channels are mixed, I'm not sure if the area painted by one channel is as expected.

Do you want to add the function of drawing or displaying a single channel in the future?
Thanks again! ❤️❤️

**Comment by oRazeD** [comment]
Hey @i-iooi-i! I don't think I want to support this in the tool, but let me help you get into a comfortable spot.

I made an example `.blend` file with a node group for displaying the separate RGB channels of your color attribute (or any 3float). 

![image](https://github.com/user-attachments/assets/0484dc81-9aac-4133-a837-b54e3fd7ace4)

To use this, all you have to do is:
1. Append or link the node group from this file to your own project
2. Create a material on the object you're working on (if one doesn't already exist)
3. Add the new node group to the material
4. Plug in a Color Attribute node and plug in the output socket of the channel you'd like to visualize
5. Head to Material Preview / Rendered viewport

DD link: https://drive.google.com/file/d/1IpSi0-pjpm2fGfgygRyOsLj1uDBocZjL/view?usp=sharing

**Comment by i-iooi-i** [comment]
> Hey @i-iooi-i! I don't think I want to support this in the tool, but let me help you get into a comfortable spot.
> 
> I made an example `.blend` file with a node group for displaying the separate RGB channels of your color attribute (or any 3float).
> 
> ![image](https://private-user-images.githubusercontent.com/31065180/362380220-0484dc81-9aac-4133-a837-b54e3fd7ace4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Mzg2MTEsIm5iZiI6MTcyNTQzODMxMSwicGF0aCI6Ii8zMTA2NTE4MC8zNjIzODAyMjAtMDQ4NGRjODEtOWFhYy00MTMzLWE4MzctYjU0ZTNmZDdhY2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA4MjUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYzcyMmZjZTRkNzc4MWVlMDJkMTNhMzAwMDYzOTc3NDlkOGUyNjUxZTFhYmNlZTdjZGViZjA4ODcxYTc2ZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fAPUYV46wRBgbfPWhrNn8HNMtpsqlNGiM4xDDmIACEM)
> 
> To use this, all you have to do is:
> 
> 1. Append or link the node group from this file to your own project
> 2. Create a material on the object you're working on (if one doesn't already exist)
> 3. Add the new node group to the material
> 4. Plug in a Color Attribute node and plug in the output socket of the channel you'd like to visualize
> 5. Head to Material Preview / Rendered viewport
> 
> DD link: https://drive.google.com/file/d/1IpSi0-pjpm2fGfgygRyOsLj1uDBocZjL/view?usp=sharing

Thank you very much for the solution, but the problem is still there, and you will get the wrong result in the process of painting.
Let me elaborate further.

**Comment by i-iooi-i** [comment]
https://github.com/user-attachments/assets/ad39688c-24b1-46a4-8f48-3c3fa2a26c83

I think the exact way to do this is to paint in different channels, no matter what color you use, and you're going to get accurate information in RGB.

**Comment by i-iooi-i** [comment]
Uploading 录制_2024_09_04_16_32_46_582.mp4…
The problem with Blender is that when I paint with different colors in the R channel, I get "inaccurate" results.

**Comment by i-iooi-i** [comment]
https://github.com/user-attachments/assets/e76fec8a-d415-4d09-8edc-840419a8de51

The problem with Blender is that when I paint with different colors in the R channel, I get "inaccurate" results.

**Comment by oRazeD** [comment]
Does the Maya version of this also prevent colors from other channels from being applied?

**Comment by i-iooi-i** [comment]
> Does the Maya version of this also prevent colors from other channels from being applied?


https://github.com/user-attachments/assets/c6eabfd4-46b0-4a03-ad15-ec7564f15c1d
Yes, the principle is the same between MAYA and PS. It's just that I can't do anything like that in Blender, and I can't even find one of these plugins. 🙈🙈🙈

**Comment by oRazeD** [comment]
This is something I could do in some capacity, but the one method I'm thinking of would only work on mesh selections in Edit Mode. I don't modify any of the Vertex Paint Mode functionality currently and I would suspect it to be a little bit difficult. If only being able to do it in Edit Mode doesn't seem good enough I probably wouldn't bother adding it.

One other question, do you have any specific use cases for this? I understand that it functions like Photoshop RGB masking layers functionality but how is this concept generally being applied in vertex color workflows in the real world? Thank you very much for these visual examples, they've helped a ton.

**Comment by i-iooi-i** [comment]
> This is something I could do in some capacity, but the one method I'm thinking of would only work on mesh selections in Edit Mode. I don't modify any of the Vertex Paint Mode functionality currently and I would suspect it to be a little bit difficult. If only being able to do it in Edit Mode doesn't seem good enough I probably wouldn't bother adding it.
> 
> One other question, do you have any specific use cases for this? I understand that it functions like Photoshop RGB masking layers functionality but how is this concept generally being applied in vertex color workflows in the real world? Thank you very much for these visual examples, they've helped a ton.


https://github.com/user-attachments/assets/670cd8e3-420a-450e-bcc6-ee417b0f140b

https://github.com/user-attachments/assets/a7ec7b3f-c2b0-4dc1-bd6a-bbae2a0d16ac

Vertex painting is commonly used in the game industry, as shown in the video, through different RGB channels, to control the three effects of skirt shaking, note jumping, and white rain. Each layer is painted separately to ensure that each color channel is correct.

Thank you so much for the plugin, I've been using it lately as well,  been great, it makes up for some of Blender's shortcomings in vertex painting. 😊💕

**Comment by oRazeD** [comment]
Hey @i-iooi-i, thank you for the visual examples. I investigated further, and I'm not sure if I can build something close enough to the experience you expect here. I've added it to my feature requests list with the extra information you've provided, so I can keep it in mind for future development pushes.

In any case, one workaround approach I found to mock your desired workflow was to utilize the Customizable Palette with its default R G B color presets and the color apply option set to `Set Color`. This option will set the color in both Edit Mode and Vertex Paint Mode:

![image](https://github.com/user-attachments/assets/aa21782e-7b53-469e-9753-033f6e5961c4)

You could then change the value without applying to other color channels on accident:

![QHMCIoK5LO](https://github.com/user-attachments/assets/fe270da3-aa7b-4973-b2a3-d0f6a83e7f74)

I also took the liberty of updating the Blend file I sent previously with options for each color channel in grayscale:

![image](https://github.com/user-attachments/assets/f11fe7e1-99c9-4b41-82a1-bc9f1b9c7f23)

I hope this helps! You lose the ability to select literally any color, but you still manage to keep the colors separated and the ability to view the individual channels in grayscale.

**Comment by i-iooi-i** [comment]
@oRazeD Hi, thank you very much for the method, It's not as easy to use as MAYA, but it's the best way I know how to do it.  This method will be convenient for people who are not used to using Maya, thank you very much. 😊😊❤️❤️

**Comment by oRazeD** [comment]
Closing, as I've already added any relevant info to my personal to-do list.
